apiVersion: v1
kind: Template
metadata:
  name: openemr-persistent
  annotations:
    description: "Template for OpenEMR, medical practice management software."
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: openemr
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mariadb
    name: mariadb
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentconfig: mariadb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openemr
    name: openemr
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      deploymentconfig: openemr
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mariadb
    name: mariadb
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: mariadb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: mariadb
      spec:
        containers:
        - args:
          - --character-set-server=utf8
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_ROOT_PASSWORD}
          image: mariadb
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mariadb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mariadb
        from:
          kind: ImageStreamTag
          name: mariadb:10.4
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: openemr
    name: openemr
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: openemr
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: openemr
      spec:
        containers:
        - env:
          - name: MYSQL_HOST
            value: mariadb
          - name: MYSQL_PASS
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_ROOT_PASS
            value: ${MYSQL_ROOT_PASSWORD}
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: OE_PASS
            value: ${OE_PASS}
          - name: OE_USER
            value: ${OE_USER}
          image: openemr
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          name: openemr
          ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 0
        serviceAccount: openemr
        serviceAccountName: openemr
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - openemr
        from:
          kind: ImageStreamTag
          name: openemr:5.0.2
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: mariadb
    name: mariadb
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker.io/mariadb:10.4
      name: "10.4"
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: openemr
    name: openemr
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: openemr/openemr:5.0.2
      name: 5.0.2
      referencePolicy:
        type: Source
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: openemr
    name: openemr
  spec:
    port:
      targetPort: 443
    subdomain: ""
    tls:
      termination: passthrough
    to:
      kind: Service
      name: openemr
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mariadb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeMode: Filesystem
parameters:
- description: Password for the MariaDB root user.
  displayName: MariaDB root Password
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Username for MariaDB user that will be used for accessing the database.
  displayName: MariaDB Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: MYSQL_USER
  value: openemr
- description: Password for the MariaDB connection user.
  displayName: MariaDB Connection Password
  name: MYSQL_PASSWORD
  required: true
- description: Name of the MariaDB database accessed.
  displayName: MariaDB Database Name
  name: MYSQL_DATABASE
  value: openemr
- description: Username for OpenEMR admin user.
  displayName: OpenEMR admin username.
  from: user[A-Z0-9]{3}
  generate: expression
  name: OE_USER
  value: admin
- description: Password for the OpenEMR admin user.
  displayName: OpenEMR admin user password.
  name: OE_PASS
  required: true
